-- Scripted from live DB [NatureKnit] on 2026-07-24 (read-only). Source of truth = database.
-- Table: dbo.tbl_knitter_recieved  (columns + PK + defaults + identity; indexes/FKs appended below)
CREATE TABLE [dbo].[tbl_knitter_recieved] (
    [id] int IDENTITY(1,1) NOT NULL,
    [item_id] int NULL,
    [item_no] varchar(200) NULL,
    [r_wt] float NULL,
    [r_date] date NULL,
    [r_time] time(7) NULL,
    [r_status] int NULL,
    [fm_status] int NULL,
    [fm_datetime] datetime NULL,
    [k_datetime] datetime NULL,
    [k_status] int NULL,
    [kf_datetime] datetime NULL,
    [kf_status] int NULL,
    [dr_datetime] datetime NULL,
    [dr_status] int NULL,
    [df_datetime] datetime NULL,
    [df_status] int NULL,
    [hr_datetime] datetime NULL,
    [hr_status] int NULL,
    [hf_datetime] datetime NULL,
    [hf_status] int NULL,
    [hd_dep] int NULL,
    [lr_datetime] datetime NULL,
    [lr_status] int NULL,
    [lf_datetime] datetime NULL,
    [lf_status] int NULL,
    [mr_datetime] datetime NULL,
    [mr_status] int NULL,
    [mf_datetime] datetime NULL,
    [mf_status] int NULL,
    [prr_datetime] datetime NULL,
    [prr_status] int NULL,
    [prf_datetime] datetime NULL,
    [prf_status] int NULL,
    [er_datetime] datetime NULL,
    [er_status] int NULL,
    [ef_datetime] datetime NULL,
    [ef_status] int NULL,
    [pcr_datetime] datetime NULL,
    [pcr_status] int NULL,
    [pcf_datetime] datetime NULL,
    [pcf_status] int NULL,
    [krc] int NULL,
    [kfc] int NULL,
    [hrc] int NULL,
    [hfc] int NULL,
    [lrc] int NULL,
    [lfc] int NULL,
    [mrc] int NULL,
    [mfc] int NULL,
    [prc] int NULL,
    [pfc] int NULL,
    [drc] int NULL,
    [dfc] int NULL,
    [cancell] int NULL,
    [knc] int NULL,
    [knfc] int NULL,
    [fwt] float NULL,
    [wtc] int NULL,
    [rej] int NULL,
    [prn_f] int NULL,
    [prnf_d] datetime NULL,
    [prn_date] date NULL,
    [prn_dep] varchar(40) NULL,
    [prn_r] int NULL,
    [prn_rdate] date NULL,
    [prn_vr] int NULL,
    [prn_fr] int NULL,
    [style_typ] varchar(50) NULL,
    [tlrf] int NULL,
    [tlr_r] int NULL,
    [tlr_date] date NULL,
    [tlr_w] int NULL,
    [tlr_wdate] date NULL,
    [tlr_wf] int NULL,
    [tlr_wfdate] date NULL,
    [wvf] int NULL,
    [wvr] int NULL,
    [wvr_date] date NULL,
    [wvn_w] int NULL,
    [wvn_wdate] date NULL,
    [wvn_wf] int NULL,
    [wvn_wf_date] date NULL,
    [wash_r] int NULL CONSTRAINT [DF__tbl_knitt__wash___31B762FC] DEFAULT ((0)),
    [wash_rdate] datetime NULL,
    [wash_f] int NULL CONSTRAINT [DF__tbl_knitt__wash___32AB8735] DEFAULT ((0)),
    [wash_fdate] datetime NULL,
    [wash_status] int NULL CONSTRAINT [DF__tbl_knitt__wash___339FAB6E] DEFAULT ((0)),
    [dep_n] varchar(20) NULL CONSTRAINT [DF__tbl_knitt__dep_n__3493CFA7] DEFAULT (''),
    [wrc] int NULL CONSTRAINT [DF__tbl_knitter__wrc__3587F3E0] DEFAULT ((0)),
    [wfc] int NULL CONSTRAINT [DF__tbl_knitter__wfc__367C1819] DEFAULT ((0)),
    [final_check] int NULL CONSTRAINT [DF__tbl_knitt__final__37703C52] DEFAULT ((0)),
    [chk_date] datetime NULL,
    [fwt_date] datetime NULL,
    [qc] int NULL CONSTRAINT [DF__tbl_knitter___qc__3864608B] DEFAULT ((0)),
    [qc_date] datetime NULL,
    [plmwt_rejection] int NULL CONSTRAINT [DF__tbl_knitt__plmwt__395884C4] DEFAULT ((0)),
    [finalwt_rejection] int NULL CONSTRAINT [DF__tbl_knitt__final__3A4CA8FD] DEFAULT ((0)),
    [sizewt] float NULL,
    [pannel_check] int NULL CONSTRAINT [DF__tbl_knitt__panne__3B40CD36] DEFAULT ((0)),
    CONSTRAINT [PK__tbl_knit__3213E83F76E87037] PRIMARY KEY CLUSTERED ([id] ASC)
);

-- Indexes
CREATE NONCLUSTERED INDEX [idx_fast_index_wr] ON [dbo].[tbl_knitter_recieved] ([wash_r] ASC, [wrc] ASC, [wash_rdate] ASC);
CREATE NONCLUSTERED INDEX [idx_fast_index_wf] ON [dbo].[tbl_knitter_recieved] ([wash_f] ASC, [wfc] ASC, [wash_fdate] ASC);
CREATE NONCLUSTERED INDEX [idx_fast_index_lr] ON [dbo].[tbl_knitter_recieved] ([lr_datetime] ASC);
CREATE NONCLUSTERED INDEX [idx_fast_index] ON [dbo].[tbl_knitter_recieved] ([item_id] ASC);
CREATE NONCLUSTERED INDEX [idx_item_no] ON [dbo].[tbl_knitter_recieved] ([item_no] ASC);
CREATE NONCLUSTERED INDEX [idx_fast_index_hf] ON [dbo].[tbl_knitter_recieved] ([hf_datetime] ASC, [hf_status] ASC);
CREATE NONCLUSTERED INDEX [idx_kacha] ON [dbo].[tbl_knitter_recieved] ([k_status] ASC, [kf_status] ASC);
CREATE NONCLUSTERED INDEX [idx_dep] ON [dbo].[tbl_knitter_recieved] ([dep_n] ASC);
CREATE NONCLUSTERED INDEX [idx_style_typ] ON [dbo].[tbl_knitter_recieved] ([prf_status] ASC, [prf_datetime] ASC);
CREATE NONCLUSTERED INDEX [idx_plmwt_rejection] ON [dbo].[tbl_knitter_recieved] ([plmwt_rejection] ASC);
CREATE NONCLUSTERED INDEX [idx_finalwt_rejection] ON [dbo].[tbl_knitter_recieved] ([finalwt_rejection] ASC);
CREATE NONCLUSTERED INDEX [idx_fm_status] ON [dbo].[tbl_knitter_recieved] ([fm_status] ASC);
CREATE NONCLUSTERED INDEX [idx_r_date] ON [dbo].[tbl_knitter_recieved] ([r_date] ASC);
CREATE NONCLUSTERED INDEX [idx_r_date_2] ON [dbo].[tbl_knitter_recieved] ([r_date] ASC);
