-- Scripted from live DB [NatureKnit] on 2026-07-24 (read-only). Source of truth = database.
-- Table: dbo.tbl_stylesheet  (columns + PK + defaults + identity; indexes/FKs appended below)
CREATE TABLE [dbo].[tbl_stylesheet] (
    [style_id] int IDENTITY(26721,1) NOT NULL,
    [style_no] varchar(200) NULL,
    [style_date] date NULL,
    [style_status] int NULL,
    [style_buyer] varchar(200) NULL,
    [style_product] int NULL,
    [style_discription] varchar(200) NULL,
    [style_remark] nvarchar(max) NULL,
    [style_ref] int NULL,
    [style_knit] varchar(100) NULL,
    [style_print] int NULL CONSTRAINT [DF__tbl_style__style__4AB81AF0] DEFAULT ((0)),
    [style_tailor] varchar(100) NULL CONSTRAINT [DF__tbl_style__style__4BAC3F29] DEFAULT ('0'),
    [style_product_id] varchar(100) NULL,
    [style_weight] int NULL,
    [style_cat] int NULL,
    [style_structure] varchar(200) NULL,
    [style_target] float NULL,
    [style_osfa] int NULL,
    [style_osize] varchar(100) NULL,
    [style_color] varchar(200) NULL,
    [style_ply] int NULL,
    [style_embd] int NULL CONSTRAINT [DF__tbl_style__style__4CA06362] DEFAULT ((0)),
    [style_oven] int NULL,
    [stripom] int NULL,
    [tyeom] int NULL,
    [stromcol] varchar(200) NULL,
    [tieomcol] varchar(200) NULL,
    [multipleyan] int NULL,
    [style_person] varchar(200) NULL,
    [collection_type] varchar(200) NULL,
    [nolink] int NULL,
    [spacedye] int NULL,
    [type] varchar(50) NULL,
    [dep] varchar(50) NULL,
    [style_guage] varchar(20) NULL,
    [style_comp] int NULL,
    [style_comp_rem] varchar(200) NULL,
    [style_printime] float NULL,
    [style_print_f] int NULL,
    [stylr_emb_time] float NULL,
    [style_tailor_type] int NULL CONSTRAINT [DF__tbl_style__style__4D94879B] DEFAULT ((0)),
    [tailoring_charge] float NULL,
    [net_wet] float NULL,
    [child_typ] int NULL CONSTRAINT [DF__tbl_style__child__4E88ABD4] DEFAULT ((2)),
    [woven_w] float NULL CONSTRAINT [DF__tbl_style__woven__4F7CD00D] DEFAULT ((0)),
    [woven_l] float NULL CONSTRAINT [DF__tbl_style__woven__5070F446] DEFAULT ((0)),
    [woven_fringe] varchar(100) NULL CONSTRAINT [DF__tbl_style__woven__5165187F] DEFAULT ('no'),
    [loom_type] varchar(100) NULL CONSTRAINT [DF__tbl_style__loom___52593CB8] DEFAULT ('0'),
    [weave_factory] varchar(100) NULL CONSTRAINT [DF__tbl_style__weave__534D60F1] DEFAULT ('0'),
    [final_measurement] int NULL CONSTRAINT [DF__tbl_style__final__5441852A] DEFAULT ((0)),
    [quick_style] int NULL CONSTRAINT [DF__tbl_style__quick__5535A963] DEFAULT ((0)),
    [parent_style] int NULL CONSTRAINT [DF__tbl_style__paren__5629CD9C] DEFAULT ((0)),
    [computer_y] int NULL,
    [tailoring_target] float NULL CONSTRAINT [DF__tbl_style__tailo__571DF1D5] DEFAULT ((0)),
    [child_size] int NULL CONSTRAINT [DF__tbl_style__child__5812160E] DEFAULT ('0'),
    CONSTRAINT [PK__tbl_styl__D333B397EFA0B242] PRIMARY KEY CLUSTERED ([style_id] ASC)
);

-- Indexes
CREATE NONCLUSTERED INDEX [idx_style_product_id] ON [dbo].[tbl_stylesheet] ([style_product_id] ASC);
